/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booking;
import javax.swing.JOptionPane;
import javax.swing.JLabel;

/**
 *
 * @author allwanzx
 */
//modul 5 oop class
public class Bookingframe extends javax.swing.JFrame {


    /**
     *
     */
//   modul 5 oop (constructor)
    public Bookingframe() {
        initComponents();
        
        uangTextField.setVisible(false);
        checkButton.setVisible(false);
        dollar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blinkcheck = new javax.swing.JCheckBox();
        radioheadcheck = new javax.swing.JCheckBox();
        coldplaycheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dewacheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        billing = new javax.swing.JLabel();
        hoho = new javax.swing.JLabel();
        uangTextField = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        dollar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        jLabel1.setText("Daftar Band");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 137, 50));

        jLabel2.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        jLabel2.setText("Tarif");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 172, 50));

        blinkcheck.setBackground(new java.awt.Color(0, 0, 0));
        blinkcheck.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        blinkcheck.setForeground(new java.awt.Color(0, 204, 204));
        blinkcheck.setText("blink-182");
        blinkcheck.setToolTipText("");
        blinkcheck.setBorderPainted(true);
        blinkcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blinkcheckActionPerformed(evt);
            }
        });
        getContentPane().add(blinkcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 140, 40));

        radioheadcheck.setBackground(new java.awt.Color(255, 255, 255));
        radioheadcheck.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        radioheadcheck.setText("Radiohead");
        radioheadcheck.setBorderPainted(true);
        getContentPane().add(radioheadcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 140, 40));

        coldplaycheck.setBackground(new java.awt.Color(255, 255, 255));
        coldplaycheck.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        coldplaycheck.setForeground(new java.awt.Color(255, 102, 255));
        coldplaycheck.setText("Coldplay");
        coldplaycheck.setBorderPainted(true);
        getContentPane().add(coldplaycheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 140, 40));

        jLabel7.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("$ 2.700.000");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 231, 41));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("$ 3.000.000");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 231, 41));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("$ 6.500.000");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 231, 47));

        jLabel10.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("$ 700.000");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 231, 41));

        dewacheck.setBackground(new java.awt.Color(0, 0, 0));
        dewacheck.setFont(new java.awt.Font("Skia", 0, 18)); // NOI18N
        dewacheck.setForeground(new java.awt.Color(0, 51, 255));
        dewacheck.setText("Dewa 19");
        dewacheck.setBorderPainted(true);
        dewacheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dewacheckActionPerformed(evt);
            }
        });
        getContentPane().add(dewacheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 40));

        jLabel3.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel3.setText("Daftar Band Tersedia Beserta Tarif");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 460, 46));

        submitbtn.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        billing.setFont(new java.awt.Font("Skia", 1, 16)); // NOI18N
        billing.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 194, 36));

        hoho.setFont(new java.awt.Font("Skia", 1, 16)); // NOI18N
        hoho.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(hoho, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 780, 74));

        uangTextField.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        uangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(uangTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 190, -1));

        checkButton.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        checkButton.setText("Bayar");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));

        dollar.setForeground(new java.awt.Color(255, 255, 255));
        dollar.setText("$");
        getContentPane().add(dollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 550, 10, 23));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/blinkhero (3).jpeg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/043894600_1451109853-radiohead_credit_jim_dyson_2012 (1).jpeg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/Coldplay_Live_Singapore_ratio-16x9 (1).jpeg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 342, 100, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/aodewashow_4 (1) Small.jpeg")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/tony-pham-FUmDe-Bx1LA-unsplash (4).jpeg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1080, 810));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blinkcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blinkcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blinkcheckActionPerformed

    private void dewacheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dewacheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dewacheckActionPerformed
//modul 4 function method
    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
      int total = 0;
    String message = "Band yang dipilih: \n";
//    modul 2 pengkondisian (if else)
    if (blinkcheck.isSelected()) {
        total += 3000000;
        message += "Blink-182 : $3.000.000\n";
    }
    if (radioheadcheck.isSelected()) {
        total += 6500000;
        message += "Radiohead : $6.500.000\n";
    }
    if (dewacheck.isSelected()) {
        total += 700000;
        message += "Dewa 19   : $700.000\n";
    }
    if (coldplaycheck.isSelected()) {
        total += 2700000;
        message += "Coldplay  : $2.700.000\n";
    }
    
    message += "\nTotal Pembayaran: $" + total ;
    
    
    {JOptionPane.showMessageDialog(null, message);} 
    
//    
    hoho.setText(message);
    billing.setText("Masukkan Uang");
    submitbtn.setVisible(false);
    
    uangTextField.setVisible(true);
    checkButton.setVisible(true);
    dollar.setVisible(true);

     
      // Memeriksa apakah total pembayaran sudah mencukupi
//      modul 1 tipe data (string)
    String uangText = uangTextField.getText();
    if (uangText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah uang.");
        return;
    }
    
    double uang;
    try {
        uang = Integer.parseInt(uangText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk jumlah uang.");
        return;
    }
    
    double kembalian = uang - total;
//    modul 2 pengkondisian (if else)
    
    if (kembalian >= 0) {
        // Total pembayaran mencukupi, tampilkan pesan terima kasih dan kembalian
//        modul 1 tipe data (string)
        String terimaKasih  = "Terima kasih telah melakukan pembayaran. \nUang Anda: $" + uang ;
        
        if (kembalian > 0) {
           
            terimaKasih += "\nKembalian Anda: $" + kembalian ;
                checkButton.setVisible(false);
        }
        JOptionPane.showMessageDialog(this, terimaKasih);
        
       
    } else {
        // Total pembayaran belum mencukupi, tampilkan pesan
        JOptionPane.showMessageDialog(this, "Uang yang Anda masukkan tidak mencukupi.");
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_submitbtnActionPerformed
// modul 4 function method
    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed

      // Memeriksa apakah total pembayaran sudah mencukupi
      
    submitbtnActionPerformed(evt);
    // Memeriksa apakah total pembayaran sudah mencukupi
            Payment payment = new Payment();
 payment.setTotalPayment(1000.0);
 double totalPayment = payment.getTotalPayment();
 


        // TODO add your handling code here:
    }//GEN-LAST:event_checkButtonActionPerformed

    private void uangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangTextFieldActionPerformed
    
          

    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookingframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookingframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookingframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookingframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookingframe().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billing;
    private javax.swing.JCheckBox blinkcheck;
    private javax.swing.JButton checkButton;
    private javax.swing.JCheckBox coldplaycheck;
    private javax.swing.JCheckBox dewacheck;
    private javax.swing.JLabel dollar;
    private javax.swing.JLabel hoho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox radioheadcheck;
    public javax.swing.JButton submitbtn;
    private javax.swing.JTextField uangTextField;
    // End of variables declaration//GEN-END:variables
}
