/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booking;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JFrame;


/**
 *
 * @author allwanzx
 */

//modul 5 class
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
//    modul 5 constructor
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IsiUser = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        IsiPW = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 151, 75, 31));

        jLabel2.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 227, 75, 31));

        IsiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiUserActionPerformed(evt);
            }
        });
        getContentPane().add(IsiUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 150, 162, 31));

        loginButton.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        loginButton.setText("Masuk");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 322, -1, -1));
        getContentPane().add(IsiPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 226, 162, 31));

        jLabel3.setFont(new java.awt.Font("Skia", 0, 22)); // NOI18N
        jLabel3.setText("Selamat Datang di Program Booking Band");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 16, 443, 56));

        jLabel4.setFont(new java.awt.Font("Skia", 0, 13)); // NOI18N
        jLabel4.setText("Silahkan masukkan username dan password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 124, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/allwanzx/Downloads/rod-long-YLtf9KqA4h0-unsplash (2).jpeg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1040, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiUserActionPerformed
//modul 4 function dan method
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
//     modul 1 tipe data (string) +modul 2 pengkondisian (if ,else) 
    String username = IsiUser.getText();
    String password = new String(IsiPW.getPassword());

    if (username.equals("allwan") && password.equals("allwan123")) {
        JOptionPane.showMessageDialog(null, "Login Berhasil");
        // Add your code here for the next action after successful login
        Bookingframe bf =  new Bookingframe();
        bf.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Login Gagal");
    }

// TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField IsiPW;
    private javax.swing.JTextField IsiUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
